name: Check linting and cypress tests

on: 
  push:
    branches: 
      - feature/*

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run CI command
      run: npm ci

    - name: Check linting
      run: npm run lint

  install:
    runs-on: ubuntu-22.04
    needs: check-lint
    container:
      image: cypress/browsers:node-20.11.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build
  
  components-test:
    runs-on: ubuntu-22.04 
    container: cypress/browsers:node-20.11.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
    strategy:
      fail-fast: false
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Components test
        uses: cypress-io/github-action@v5
        with:
          component: true
          start: npm start
          browser: chrome    


